#
# A simple container build.
# The variable CONTAINER_ID is defined in the job environment variables
# Then variables DockerUser and DockerPassword are defined in the 'context' DockerHub
#

version: 2.1

workflows:
  build:
    jobs:
      - build-container:
          context: DockerHub

jobs:
  build-container:

# CircleCI maintains a library of pre-built images
# documented at https://circleci.com/docs/2.0/circleci-images/
# You can also use any images defined on Docker Hub.
# Here it is using a public image from DockerHub
# If you are using a private iamge you will need to specify the
# username and password to pull the image

    docker:
      # specify the version
      - image: docker:18.06.3-ce-git
#      - image: docker:17.07.0-ce-git
#      - image: circleci/golang:1.16.3
#        auth:
#          username: $DockerUser
#          password: $DockerPassword
#

    working_directory: /go/src/github.com/mandelbrot-go-example
    steps:
      - checkout
      - setup_remote_docker:  #(2)
          docker_layer_caching: true # (3)

      - run:
          name: Build the application container image
          command: |
            docker build -t ${CONTAINER_ID} . -f go-server/Dockerfile
      
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo ${DockerPassword} | docker login -u ${DockerUser} --password-stdin  https://index.docker.io/v1/
              docker tag ${CONTAINER_ID} "${DockerUser}/${CONTAINER_ID}:${CIRCLE_SHA1}"
              docker push  ${DockerUser}/${CONTAINER_ID}:${CIRCLE_SHA1}
            fi

