# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.16.3
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/mandelbrot
    steps:
      - checkout
      - setup_remote_docker:  #(2)
          docker_layer_caching: false # (3)

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
        # - run: go test -v ./...
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t ${DOCKER_USER}/${CONTAINER_ID}:${CIRCLE_BUILD_NUM} .
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} https://index.docker.io/v1/
              docker push  ${DOCKER_USER}/${CONTAINER_ID}:${CIRCLE_BUILD_NUM}
            fi